### ISSUE TITLE
Fails to start when opening new desktop file

### ISSUE THREAD

**Issue by sebastianst** [gerasev-kirill/light-desktop-item-edit#3]
Hi,

I think this is related to the changes introduced in #2. Running ldie on a new file now returns an error
```
$ light-desktop-item-edit jd-gui.desktop
/usr/lib/python2.7/site-packages/ldie/desktop_edit.py:43: Warning: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  os.path.join(self.file_path, 'desktop-item-edit.ui'))
/usr/lib/python2.7/site-packages/ldie/desktop_edit.py:43: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  os.path.join(self.file_path, 'desktop-item-edit.ui'))
/usr/lib/python2.7/site-packages/ldie/desktop_edit.py:43: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  os.path.join(self.file_path, 'desktop-item-edit.ui'))
Traceback (most recent call last):
  File "/usr/bin/light-desktop-item-edit", line 57, in <module>
    app=ldie.DesktopMainWindow(DATA_PATH, argv[0],"light-desktop-item-edit")
  File "/usr/lib/python2.7/site-packages/ldie/desktop_edit.py", line 69, in __init__
    self.load_desktop_file()
  File "/usr/lib/python2.7/site-packages/ldie/desktop_edit.py", line 209, in load_desktop_file
    self.load_icon()
  File "/usr/lib/python2.7/site-packages/ldie/desktop_edit.py", line 184, in load_icon
    self.load_default_icon()
AttributeError: 'MainWindow' object has no attribute 'load_default_icon'
```
I guess if the file is new, the load icon stuff should be skipped altogether...

Cheers, Sebastian

**Comment by gerasev-kirill** [comment]
f38a55eed053feb5555aa55400f6001640a4a76b

try it

**Comment by sebastianst** [comment]
Thanks, that works!
